project:
  type: website
  output-dir: docs

website:
  title: "魔狸アンテナ"
  site-url: https://tanukima.github.io/glc/
  navbar:
    right:
      - icon: github
        href: https://github.com/TanukiMa
      - icon: twitter
        href: https://twitter.com/Matanuki
  google-analytics: "G-4G27MWJGGT"

format:
  html:
    theme: simplex
    css: styles.css
    toc: true

