project:
  type: website
  output-dir: docs

website:
  title: "魔狸アンテナ"
  favicon: favicon.svg
  site-url: https://tanukima.github.io/glc/
  google-analytics: "G-H2RKMETCK8"
  navbar:
    right:
      - icon: github
        href: https://github.com/TanukiMa/glc
      - icon: twitter
        href: https://twitter.com/Matanuki

format:
  html:
    theme: simplex
    css: styles.css
    toc: true

